plugins{
    id 'java-platform'
}

description 'ht.eyfout.junit BOM'
dependencies {
    constraints {
        project(":libraries").subprojects.forEach {
            api(project(it.path))
            println("\t - including ${it.name} in the BOM.")
        }
    }
}

javaPlatform {
    allowDependencies()
}